server:
  port: 8007

spring:
  application:
    name: Livestart-settlement
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/live_start?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        enabled: false
      password: nacos
      username: nacos
  data:
    redis:
      host: 127.0.0.1
      port: 6379

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: Livestart_settlement-service_common-message-execute_pg
    send-message-timeout: 2000

springdoc:
  default-flat-param-object: true
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.mongxin.livestart.settlement

knife4j:
  enable: true
  setting:
    language: zh_cn
